# API Configuration
api_key: "ffSke6Zx183B9ihJvP"
api_secret: "nU8Q5KSDYWQoWHjNIQKsi56qkY6lZkzZr0fi"

# Market Configuration
symbol: "BTCUSDT"
timeframe: "1h"
market_type: "linear"
margin_type: "isolated"

# Trading Parameters
initial_balance: 10000
leverage: 1
risk_per_trade: 0.02
commission: 0.0006
min_signal_confidence: 0.6

# Backtest Configuration
backtest_days: 30
min_data_points: 100
analysis_cache_timeout: 60

# Asset Configuration
asset_precision: 3 # BTC precision
price_precision: 2 # USDT precision

# Strategy Parameters
min_adx: 25
min_volatility: 0.5
max_correlation: 0.7
